[project]
name = "pisite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "flask-wtf>=1.2.2",
    "gpiod>=2.4.0",
    "gunicorn>=23.0.0",
]
